# DSA Courses

## The ADAPT Model: Background

The **A**ll-campus **D**ata Science and **A**I **P**roject-based **T**eaching and learning model ([ADAPT course model](https://datascienceacademy.ncsu.edu/courses/course-model/)) consists of three primary components:

1) [Project-Based Learning.]{.NCSUred}

Each DSA course involves a project, or mini-projects, as a framework for students to apply and demonstrate their learning in an application-focused context.

2) [10 Common Learning Elements.]{.NCSUred}

Data science is an interdisciplinary field. The 10 common learning elements are overarching objectives that can be considered across all DSA courses as a means to broaden students experiences within and beyond a given data science or AI topic.

3) [Workforce Preparedness.]{.NCSUred}

DSA courses are designed to prepare students for work - in general - in recognition of the importance, impact, and prevalence of data and AI in current and future settings across all fields. The workforce preparedness focus of the ADAPT model can be realized through providing students with opportunities to engage in relevant choices and decisions that directly and positively impact their DSA course processes, facilitating learning and skill retention that carries forward beyond the academic environment and into their next steps. Furthermore, informed choices and agency are skills that can be enhanced through experience and are central components of a daily workflow. Skills in data science and AI are enhanced through core concepts and innovative special topics aligned with future-forward workforce developments and employer needs.


## Classroom Considerations

Each of our courses are 1 credit. University [Contact/Credit Hour Guidelines](https://oucc.dasa.ncsu.edu/courses/contact-credit-hours/) set the expectation that this amounts to approximately 3 hours of student time per week (e.g., 50 minute class, two hours outside of class).

 - Please keep the expected time guidelines in mind when designing your course and related activities. In addition, please use student feedback to adjust accordingly.
 
### Implementation

A challenge that can arise in the DSA course teaching process involves how to go about effectively relaying the information that you want students to receive as you consider the course structure and time limitations. 

These constraints make for interesting design challenges and many creative course experiences follow.

 **A Few Guidelines**

As a guide, one method to address the course implementation structure is to consider developing your essential concepts based on the desired project outcomes. Consider the following:

 - Planning your instruction based on the question "What are the few and essential points students need to know to accomplish [this step in the project]?". This may serve as the contents of a given lecture within the project-based focus.
 
 - Building your course assignments as components of the project can allow students to create their products over time (as projects typically occur in real world/workforce settings) and can keep course workloads consistent and manageable. Furthermore, the project outcomes and goals can motivate the learning outcomes and the related assignments, and grounds them in application-focused explicitly-relevant contexts. Projects built over time can culminate with student presentations, reports, and similar communicative experiences.

 - Another framework to consider for planning your course delivery is the [Launch (20 minutes) -> Explore (20 minutes) -> Discuss (10 minutes)](https://drive.google.com/file/d/13AwDhsoMFh31YdHoxdP_5FaaqUdqkM1W/view) framework, where the key concepts are presented within 20 or so minutes of the "launch", and time is allotted for students to actively participate through practice/development and discussion within a class, or with significant frequency (Explore & Discuss). These time frames are a just a reference point and if implemented will naturally vary from class to class.
    - Example: (50 minute class - launch, discuss, explore) Project Step 1 - Key Concepts -> Weekly Key Concepts Discussions -> In class work and getting started on Project Step 1/assignment 1.

**Additional Considerations**

As you develop your course, consider *how you will assess the students' projects*. 

 - In determining this criteria, it is helpful to clearly present the assessment criteria to students. For example, you may have a rubric on which project assessments are based, and you can share this with the students in advance so that the project expectations are clear. Developed assessment criteria can also serve as a project building guide.
 
Balancing grading time and data science project work can be a challenge. Consider how you might be able to *incorporate structured and unstructured learning/feedback opportunities for students*. 

 - Example: As you present your key lesson concepts, you may incorporate student questions that have an auto-grading feature (structured). Subsequently, you may allow them to practice similar concepts on their own datasets as a component of their project work (unstructured).
 
**Feedback from Educational Research**

Dr. Sunghwan Byun and Dr. Jeanne McClure offer additional suggestions here: [Educational Research at the Data Science Academy - Insights from 2022-2023](https://docs.google.com/document/d/1jRILSc0DsFm2moet9Ep8bF1suEOfHfnLzfJ2t4tIfjA/edit?usp=sharing). This document contains information on what may work well and what my require more attention within the DSA course instructional process, based on certain aspects of student feedback.


      