# To Do - Weekly

## Weekly Reminders

### Week 1:

 1) Check the [NCSU Academic Calendar](https://studentservices.ncsu.edu/calendars/academic/) to note important dates (e.g., Wellness Days, Spring/Fall Break, Drop/Revision Deadline), so that you can plan your instruction/schedule accordingly.
 
 2) Add your course syllabus to your `Course Folder` (The link will be shared with you).
 
 3) Send out [DSA Course Feedback Questionnaire: Part 1 of 3]{.NCSUred} (Provide your students with the link here: https://forms.gle/YeY6TvE9Qvf6YYWM9).
 
 -  ✅ Provide 5 minutes of class time for completion.
 
### Week 2:

 1) Remind students to complete **DSA Course Feedback Questionnaire: Part 1 of 3** by the end of the week.

 2) Notify students about the [Course Collaboration Leaders Support & More](https://docs.google.com/document/d/1NcZ8ZncBXo6qcjaT3q-iSM9G4haufubMjYXbulVi_Zs/edit?usp=sharing) resource, and add this to your moodle page/course management system.
 
 3) **Research Consent Forms**. During Week 2 a DSA representative will come to your classroom. Please plan to allow five minutes at the end of the week 2 class for this representative to speak to students about the DSA research consent process. You will be asked to leave the room (or Zoom space) during this presentation to preserve students' confidentiality. 

  NOTE: As with the student reflections, please encourage participation in completing the consent forms. Students will have the option to consent or decline. A link will be provided so that you can relay this to students who have not completed the form, and/or were not present in week 2.
  
 4) (Optional for pre-post feedback): Schedule a pre-observation discussion meeting with the Teaching Coordinator.
 
### Week 3:

 1) Remind students about the [Course Collaboration Leaders Support & More](https://docs.google.com/document/d/1NcZ8ZncBXo6qcjaT3q-iSM9G4haufubMjYXbulVi_Zs/edit?usp=sharing) resource.

 2) DSA Course Feedback Questionnaire: Part 1 of 3 de-Identified feedback/responses will be returned to you.

### Week 4:

 1) Suggestion (if not already done): introduce course project, expectations, and how it is/will be integrated into/throughout the course. 

### Week 5:

 1) Remind students about the Course Collaboration Leaders Support & More resource.

### Week 6:

 1) Send out [DSA Course Feedback Questionnaire: Part 2 of 3]{.NCSUred} (Provide your students with the link here: https://forms.gle/5bDLpXa619fmFU6R6).
 
  -  ✅ Provide 5 minutes of class time for completion.
 
### Week 7:

 1) (Optional) Send two calendar invites for two different classes of your choice between Week 8 and Week 14 to Teaching Coordinator for an observation. If online, please include class meeting link in the invite.

 2) **Progress Reports**. Please refer to this link [Academic Progress Reporting](https://dasa.ncsu.edu/faculty-resources/academic-progress-reporting/). Please complete a report for any student for whom you may be concerned (e.g., not attending, not completing assignments, at risk for not successfully completing the course, etc.). Instructions on completing these reports through mypack portal are available at the link above.
 
 - ✅  Please submit any related student reports on or before this week.
 
 - ✅  Please notify the Teaching Coordinator of any outstanding concerns.
 
 3) Remind students to complete **DSA Course Feedback Questionnaire: Part 2 of 3** by the end of the week.
 
  - ✅ Provide 5 minutes of class time for completion.

### Week 8 - Week 10:

 1) Remind students about the Course Collaboration Leaders Support & More resource.
 
 2) **DSA Course Feedback Questionnaire: Part 2 of 3** de-Identified feedback/responses will be returned to you.

### Week 11:

 - Communicate Final Project Plan (e.g., weeks due, presentations/reports - a form will be provided).

### Week 12:

1) Send out [DSA Course Feedback Questionnaire: Part 3 of 3]{.NCSUred} (Provide your students with the link here: https://forms.gle/2zWRCBxt27UJtxfcA).

 -  ✅ Provide 5 minutes of class time for completion.

### Week 13:

1) Remind students to complete **DSA Course Feedback Questionnaire: Part 3 of 3** by the end of the week.

2) Add the Teaching Coordinator to your course management space with administrative access (e.g., Moodle as a "hidden instructor" and non-expiring time frame).

 - In moodle, at the "My current courses" section, scroll to your current course and... 
      - click on the "gears" icon,
      - scroll down to "users and roster," and click "edit,"
      - go to "add a person by name or unityID," and type in djstokes, and search
      - for "role" select "hidden instructor" and add the "begin date,"… you should be able to leave end date blank (non-expiring).

### Week 14 - 16:

1) Refer to the [NCSU Academic Calendar](https://studentservices.ncsu.edu/calendars/academic/) to see when final grades are due. Refer to this link [Grade Roster](https://sis.emas.ncsu.edu/faculty/faculty-center/#grades) for how to submit grades. 

2) Add all student work to your **Course Folder**, assignments and project(s) (Find your class link here: [Course Documentation Links - Spring 2025](https://docs.google.com/spreadsheets/d/1_DmMR9ZCwyfQANZCm5m6aNaB_nYunzciZFr8awdDJLw/edit?usp=sharing)).

-  ✅ Complete the following form: [Instructor Course and Work Collection Documentation - Fall 2024](to be provided)

