# Instructional Feedback & Observations

Feedback on student reflections will be given to you at least for parts 1 and 2 of 3. Beyond this standard, optional instruction observations, meetings, and/or additional feedback can be scheduled throughout the semester. Formats include:

 - Scheduling a pre-observation discussion, observation, and post-obeservation discussion.
 - Scheduling the pre and post observations around student survey/reflection feedback.
 - Scheduling a single observation with feedback.
 - Combinations of the above, or other ideas of interest.
 
 As you consider these options, please note the timelines for when the observations may work best (e.g., as indicated in the weekly information in Section 3).
 
 Outside of coordinated observations, observations may be scheduled for the purposes of understanding DSC course implementation. You will be notified in advance any such instance. You may receive a request to provide some class details (e.g., Zoom link information, general course topic/activity).

